<?php

namespace App\Controller\Admin;

use App\Entity\Chapter;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;

class ChapterCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Chapter::class;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('title'),
            DateTimeField::new("date_uploads")->hideOnForm(),

            AssociationField::new("manga")
                ->setFormTypeOption("choice_label", "title")
        ];
    }
    //Auto completion de la date d'ajout des mangas
    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        if (!$entityInstance instanceof Chapter) return;

        $entityInstance->setDateUploads(new \DateTimeImmutable);

        parent::persistEntity($entityManager, $entityInstance); // TODO : Change the autogenerated stub
    }
}
